#!/bin/zsh

tmp=/tmp/domain_rrs_list

find_resource_record_set_get_list() {
	echo "refresh list"
	aws route53 list-resource-record-sets --hosted-zone-id XXXXXXXXXX >$tmp
}


## If the cache is out of date or non-existent
find_resource_record_set_cache_is_old() {
	[[ ! -e "$tmp" ]] && return 0
	local duration=300 #sec
	local now=$(date +%s)
	local ts=$(stat -f %Sm -t %s $tmp)
	[[ $(($now - $ts)) -gt $duration ]] && return 0 || return 1
}

find_resource_record_set() {
	local host=$1
        # check file and timestamp
	find_resource_record_set_cache_is_old && find_resource_record_set_get_list
	cat $tmp | jp -u 'ResourceRecordSets[?contains(Name,`"'$host'"`) && Type==`"A"`].Name| join (`"\n"`,@)' | grep $host --color=auto
}

find_resource_record_set "$@"
