


# history size
HISTSIZE=100000



# settings for my development
alias cgdirh='cd $(ghq list --full-path | peco --query hacker65536)'
alias cgdir='cd $(ghq list --full-path | peco )'


# settings for cargo (rust)
# export PATH="$HOME/.cargo/bin:$PATH"


# settings for gc sdk
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/ec2-user/google-cloud-sdk/path.bash.inc' ]; then . '/home/ec2-user/google-cloud-sdk/path.bash.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/home/ec2-user/google-cloud-sdk/completion.bash.inc' ]; then . '/home/ec2-user/google-cloud-sdk/completion.bash.inc'; fi


# settgings for lua
# eval $(luarocks path --bin)



# settings for  Pulumi 
# export PATH=$PATH:$HOME/.pulumi/bin


# Uncomment the following line if you don't like systemctl's auto-paging feature:
#  export SYSTEMD_PAGER=
